name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Erlang and Elixir
        uses: ./.github/actions/setup-asdf-with-cache

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Erlang and Elixir
        uses: ./.github/actions/setup-asdf-with-cache

      - name: Cache Mix deps and build
        uses: actions/cache@v4
        with:
          key: mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            mix-
          path: |
            deps
            _build

      - name: Install dependencies
        run: mix deps.get

      - name: Compile with warnings as errors
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
